baseURL: https://erikaspace.netlify.app/
languageCode: en
DefaultContentLanguage: en
title: Blog of Érika S.M.B.
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
params:
  author: Érika S.M.B.
  customCss: []
  customJs: []
  description: Welcome to my amazing Data Analytic World
  doNotLoadAnimations: no
  favicon: favicons/eu2.ico
  images: images/site-feature-image.png
  keywords: ''
  mainSections: post
  math:
    enable: no
    use: katex
  profilePicture: images/eu2.jpeg
  simpleAnalytics: {}
  socialIcons:
    - icon: fab fa-linkedin
      title: Linkedin
      url: https://www.linkedin.com/in/erika-soares-machado-08951214a/
    - icon: fab fa-github
      title: GitHub
      url: https://github.com/erikastats
    - icon: fab fa-instagram
      title: instagram
      url: https://www.instagram.com/erika_abonita/?hl=pt-br
    - icon: fas fa-envelope
      title: e-mail
      url: mailto:erikasoaresm@hotmail.com
  title: I'm Erika
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 100
    - identifier: posts
      name: Posts
      url: /post/
      weight: 200
    - identifier: about
      name: About
      url: /about/
      weight: 300
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 400
